version: '3.3'
services:
  webapp:
    image: papierlos:latest
    build:
      context: perl6-papierlos
      dockerfile: Dockerfile
    ports:
      - "9080:80"
  elk-suchmaschine:
    image: elk-searchengine:latest
    build:
      context: elk-searchengine
      dockerfile: Dockerfile
